services:
  - type: web
    name: bhaidooj-birthday-site
    env: static
    buildCommand: echo "Static site - no build required"
    staticPublishPath: ./bhaidooj
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
